### ISSUE TITLE
It was not clear how to use it with pure Javascript.

### ISSUE THREAD

**Issue by vic-badaro** [stephenscaff/animated-cursor#3]
The examples given are in scenarios with React.

**Comment by stephenscaff** [comment]
@vic-badaro Where are you seeing React examples? 

[The readme's usage examples](https://github.com/stephenscaff/animated-cursor#%EF%B8%8F-usage) documents the process in JS (no react). 

[The demo](https://github.com/stephenscaff/animated-cursor/tree/master/demo/src) is a pure JS project.

I have a react version of this plugin, but there's no react in this package, examples, demo.


Pulled from the [Quickstart](https://github.com/stephenscaff/animated-cursor/blob/master/readme.md#-quickstart)

#### 1. Install from NPM

`npm i animated-cursor`

#### 2. Create Cursor Markup

```
<div id="cursor">
  <div id="cursor-outer"></div>
  <div id="cursor-inner"></div>
</div>
```

#### 3. Init Cursor

Import and initialize. Example is using defaults but accepts an options parameter (see below)
```
import AnimatedCursor from 'animated-cursor'

// Using just default options 
const ac = AnimatedCursor()

ac.init()
```

### Pass Options 

```
import AnimatedCursor from 'animated-cursor'

// cursor options
let acOptions = {
  color: '#0ff',
  outerAlpha: 0.25,
  size: { 
    inner: 8, 
    outer: 38 
  },
  hoverScale: {
    inner: 0.5,
    outer: 1.4
  },
  clickScale: {
    inner: 1.4,
    outer: 0.1
  }
}

// Create Cursor instance
const cursor = AnimatedCursor(acOptions)

// Init Cursor
cursor.init()
```

**Comment by stephenscaff** [comment]
@vic-badaro  

Oh, if you were looking to do it via CDN, or from an internally added script:

To include via CDN, find the latest UMD version at https://unpkg.com/animated-cursor and include via script tag, like so:

<script src="https://unpkg.com/animated-cursor@1.1.1/dist/index.umd.js"></script>

then call and init:

const ac = window.animatedCursor()

ac.init()


[Here's a working example](https://codepen.io/StephenScaff/pen/poVxNoB)
