### ISSUE TITLE
hasRequiredStyles option has wrong key name in documentation

### ISSUE THREAD

**Issue by joh-sch** [stephenscaff/animated-cursor#4]
I've noticed that the option `useRequiredStyles` mentioned in the documentation should be called `hasRequiredStyles`, according to the source code, [see line 12 of animated-cursor.js](https://github.com/stephenscaff/animated-cursor/blob/ccb9e9b9d401424580a0c4a4cb2868ce2a4a2613/src/animated-cursor.js#LL12C27-L12C27):

```
const defaultOptions = {
  ...
  hasRequiredStyles: true,
  ...
}
```

And [line 61](https://github.com/stephenscaff/animated-cursor/blob/ccb9e9b9d401424580a0c4a4cb2868ce2a4a2613/src/animated-cursor.js#LL61C8-L61C8), again referencing `hasRequiredStyles` and not `useRequiredStyles`:

```
function AnimatedCursor(options) {
  // merge defaults with user options
  let opts = Object.assign({}, defaultOptions, options);

  let settings = {
    ...
    hasRequiredStyles: opts.hasRequiredStyles,
    ...
  }
```

**Comment by stephenscaff** [comment]
Thanks for the heads up. 

V1.1.2 updates the docs to reflect `hasRequiredStyles`.
